config/routes.rb
Rails.application.routes.draw do
  devise_for :user_pet_cares
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :animals
  resources :adoptions, only: [:index, :show, :new, :create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :animals, only: [:show, :index, :create]
      resources :adoptions, only: [:index, :show] do
        patch 'adopt', on: :member
      end
    end
  end
end

app/models/adoption.rb
class Adoption < ApplicationRecord
    belongs_to :animal
    belongs_to :user_pet_care
    validates :title, presence: true
    validates :animal, uniqueness: true
    validates :title, length: {maximum: 40}
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_one :adoption
    belongs_to :user_pet_care
    validates :name, :age, :city, presence: true
    has_one_attached :image, :dependent => :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_pet_care.rb
class UserPetCare < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :animals
  has_many :adoptions
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
    before_action :authenticate_user_pet_care!
    before_action :set_adoption_and_check_user, only: [:destroy, :show]

    def new
        @adoption = Adoption.new
        @user = current_user_pet_care
        @animals = @user.animals
    end

    def index
        @adoptions = current_user_pet_care.adoptions
    end

    def create
        @user = current_user_pet_care
        @adoption = Adoption.new(params.require(:adoption).permit(:title, :description, :animal_id).merge(user_pet_care_id: @user.id))
        if @adoption.save
            redirect_to adoptions_path, notice: 'Adoção cadastrada com sucesso!'
        else
            flash.now[:notice] = 'Adoção falhou!'
            @animals = @user.animals
            render 'new'
        end
    end

    def destroy

        if @adoption.delete
            redirect_to(root_path, notice: 'Adoção cancelada com sucesso!')
        else
            flash.now[:notice] = "Não foi possível cancelar a adoção"
            render 'show'
        end
    end

    def show
    end

    private 
    
    def set_adoption_and_check_user
        @adoption = Adoption.find(params[:id])
        if @adoption.user_pet_care != current_user_pet_care
            return redirect_to(root_path, notice: 'Não foi possível completar a ação.')
        end
    end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    before_action :authenticate_user_pet_care!
    before_action :set_animal_and_check_user, only: [:show, :edit, :update, :destroy]
    

    def index
        @animals = current_user_pet_care.animals
    end

    def new
        @animal = Animal.new()
        @user = current_user_pet_care
    end

    def create
        @user = current_user_pet_care
        @animal = Animal.new(params.require(:animal).permit(:name, :sex, :age, :city, :animal_type, :image).merge(user_pet_care_id: @user.id))
        if @animal.save
            redirect_to(animals_path, notice: 'Animal cadastrado com sucesso!')

        else
            flash.now[:notice] = 'Verifique os erros abaixo'
            render 'new'
        end
    end

    def show 
    end

    def edit
    end

    def destroy
        if @animal.adoption.nil?
            @animal.destroy!
            redirect_to(animals_path, notice: 'Animal excluído com sucesso!')
        else
            flash.now[:notice] = 'Não foi possível excluir o animal. Ele está em adoção.'
            render 'show'
        end
    end

    def update

        if @animal.update(params.require(:animal).permit(:name, :sex, :age, :city, :animal_type).merge(user_pet_care: current_user_pet_care))
            redirect_to(animal_path(@animal.id), notice: 'Animal editado com sucesso')
        else
            flash.now[:notice] = 'Não foi possível realizar a edição'
            render 'new'
        end
    end

    private

    def set_animal_and_check_user
        @animal = Animal.find(params[:id])
        if current_user_pet_care != @animal.user_pet_care
            redirect_to(root_path, notice: 'Não foi possível realizar a ação!')
        end
    end
end

app/controllers/api/v1/adoptions_controller.rb
class Api::V1::AdoptionsController < ActionController::API
  def index
    adoptions = Adoption.joins(:animal).where('animals.adopted is FALSE')
    response = []
    adoptions.each do |adoption|
      response << {id: adoption.id, title: adoption.title, description: adoption.description,
                   city: adoption.animal.city, animal_type: adoption.animal.animal_type, animal_id: adoption.animal.id
                  }
    end
    render status: 200, json: response
  end

  def show
    adoption = Adoption.find(params[:id])
    response = {id: adoption.id, title: adoption.title, description: adoption.description, user_pet_care: adoption.user_pet_care.name,
                city: adoption.animal.city, animal_type: adoption.animal.animal_type, age: adoption.animal.age, 
                sex: adoption.animal.sex, animal_name: adoption.animal.name, animal_id: adoption.animal.id}                     
    render status: 200, json: response
  end

  def adopt
    adoption = Adoption.find(params[:id])
    adoption.animal.update(adopted: true)
    render status: 200, json: {message: "Animal adotado com sucesso! Esperamos que você e #{adoption.animal.name} sejam muito felizes."}
  end
end

app/controllers/api/v1/animals_controller.rb
class Api::V1::AnimalsController < ActionController::API

  def show
    begin
      animal = Animal.find(params[:id])
      render status: 200, json: animal.as_json(except: [:created_at, :updated_at])
    rescue  
      render status: 404
    end
  end

  def index
    animals = Animal.all
    render status: 200, json: animals.as_json(except: [:created_at, :updated_at])
  end

  def create
    @animal = Animal.new(params.require(:animal).permit(:name, :sex, :age, :city, :animal_type, :user_pet_care_id))
    if @animal.save
      render status: 201, json: @animal.as_json(except: [:created_at, :updated_at])
    else
      render status: 407
    end
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :city])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
       
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adoptions/index.html.erb
<h2> Minhas adoções <h2>

<div>
  <% @adoptions.each do |adoption| %>
    <%= link_to adoption.title, adoption_path(adoption)%>
    Nome: <%= adoption.animal.name %>
  <% end %>
</div>

app/views/adoptions/new.html.erb
<% if @adoption.errors.full_messages.any? %>
    
    <ul>
    <% @adoption.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
    <% end %>
    </ul>

<% end %>

<%= form_with model: @adoption do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %> <br>

    <%= f.label :description %>
    <%= f.text_area :description %> <br>

    <%= f.label :animal_id %>
    <%= f.collection_select :animal_id, @animals, :id, :name %> <br>

    <%= f.submit 'Cadastrar adoção' %>

<% end %>

app/views/adoptions/show.html.erb
<h1>Visualizando adoção de <%= @adoption.animal.name %> </h1>

<div>
  <h3> <%= @adoption.title %> </h3>
  <p> <%= @adoption.description %> </p>
  <p><%=Animal.human_attribute_name(:name)%>: <%= @adoption.animal.name %> </p>
  <p> <%= @adoption.animal.sex %> </p>
  <p> <%= @adoption.animal.animal_type %> </p>
  <p> <%= @adoption.animal.age %> anos</p>
  <p>Cuidador: <%= @adoption.user_pet_care.name %> < <%= @adoption.user_pet_care.email %> > - <%= @adoption.user_pet_care.city %></p>
</div>

<%= button_to 'Cancelar adoção', adoption_path(@adoption), method: :delete %>

app/views/animals/edit.html.erb
<% if @animal.errors.full_messages.any? %>
    
    <ul>
    <% @animal.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
    <% end %>
    </ul>

<% end %>


<%= form_with model: @animal do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.radio_button(:sex, I18n.t(:male)) %>
    <%= f.label(:sex, I18n.t(:male)) %>

    <%= f.radio_button(:sex, I18n.t(:female)) %>
    <%= f.label(:sex, I18n.t(:female)) %> <br>

    <%= f.label :age %>
    <%= f.text_field :age %> <br>

    <%= f.label :animal_type %>
    <%= f.text_field :animal_type %> <br>

    <%= f.label :city %>
    <%= f.text_field :city %> <br>

    <%= f.submit 'Editar animal' %>

<% end %>

app/views/animals/index.html.erb
<h1> Animais cadastrados </h1>

<% if @animals.any? %>

    <% @animals.each do |a| %>

        <div>
            <p><%= link_to a.name, animal_path(a.id) %> - <%= a.animal_type %> </p>
            
        </div>

    <% end %>
<% else %>
    <h2>Não há animais cadastrados!</h2>
<% end %>

app/views/animals/new.html.erb
<% if @animal.errors.full_messages.any? %>
    
    <ul>
    <% @animal.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
    <% end %>
    </ul>

<% end %>


<%= form_with model: @animal do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.radio_button(:sex, I18n.t(:male)) %> 
    <%= f.label(:sex, I18n.t(:male)) %>

    <%= f.radio_button(:sex, I18n.t(:female)) %>
    <%= f.label(:sex, I18n.t(:female)) %> <br>

    <%= f.label :age %>
    <%= f.number_field :age, step: :any %> <br>

    <%= f.label :animal_type %>
    <%= f.collection_select :animal_type, ['Gato', 'Cachorro', 'Porco', 'Pássaro', 'Hamster', 'Capivara'], :to_s, :to_s  %> <br>

    <%= f.label :city %>
    <%= f.text_field :city %> <br>

    <div class="form-group">
        <% if @animal.image.attached? %>
            <%= image_tag @animal.image, style: "width: 200px; display: block"%>
        <% end %>

        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control"%>
    </div>

    <%= f.submit 'Cadastrar animal' %>

<% end %>

app/views/animals/show.html.erb
<h1>Visualizando <% @animal.name %> </h1>

<div>
    <ul>
        <li>Nome: <%=@animal.name%></li>
        <li>Sexo: <%=@animal.sex%></li>
        <li>Idade: <%=@animal.age%></li>
        <li>Tipo de animal: <%=@animal.animal_type%></li>
        <li>Cidade: <%=@animal.city%></li>
        <li>Cuidador: <%=@animal.user_pet_care.name%></li>
    </ul>
</div>

<% if @animal.image.attached? %>
    <%= image_tag @animal.image, style: "width: 200px; display: block"%>
<% end %>

<div>
    <%= button_to 'Excluir animal', animal_path(@animal.id), method: :delete %>
</div>

<div>
<%= link_to 'Editar animal', edit_animal_path(@animal.id) %>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="container d-flex justify-content-center text-center">
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to 'Minhas adoções', adoptions_path, class: "btn btn-menu btn-lg mt-4"  %>
      <%= link_to 'Cadastrar animal para adoção', new_adoption_path, class: "btn btn-menu btn-lg mt-3"  %>
      <%= link_to 'Meus animais cadastrados', animals_path, class: "btn btn-menu btn-lg mt-3"  %>
      <%= link_to 'Realizar cadastro de animal', new_animal_path, class: "btn btn-menu btn-lg mt-3"  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoptionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-2 mb-4 border-bottom">
       <a class="navbar-brand ms-2" href="<%= root_path %>">
          <%= image_tag 'dog-cat.svg', height: 50, width: 70 %>
          <h2 class="d-inline p-2 mt-5"> Me adota ai</h2>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 me-5">
          <li>Cadastro de animais para adoção online</li>
        </ul>

        <div class="col-md3 text-end me-4">
          <% if user_pet_care_signed_in? %>
              Olá, <%= current_user_pet_care.name %>
              <%= button_to 'Sair', destroy_user_pet_care_session_path, method: :delete, class: "btn btn-danger mt-2" %>
          <% else %>
            <div>
              <%= link_to 'Log in', new_user_pet_care_session_path, class: "btn btn-outline-primary"%>
              <%= link_to 'Registre-se', new_user_pet_care_registration_path, class: "btn btn-primary"%>
            </div>
          <% end %>
        </div>
      </header>
    </div>
    

    <div>
      <div>
        <%= notice %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>